# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draw.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_scissor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_scissor.setGeometry(QtCore.QRect(552, 1000, 200, 60))
        self.pushButton_scissor.setObjectName("pushButton_scissor")
        self.pushButton_source = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_source.setGeometry(QtCore.QRect(176, 1000, 200, 60))
        self.pushButton_source.setObjectName("pushButton_source")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(928, 1000, 200, 60))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_clean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clean.setGeometry(QtCore.QRect(1304, 1000, 200, 60))
        self.pushButton_clean.setObjectName("pushButton_clean")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_scissor.setText(_translate("MainWindow", "裁剪多边形"))
        self.pushButton_source.setText(_translate("MainWindow", "目标多边形"))
        self.pushButton_save.setText(_translate("MainWindow", "确定"))
        self.pushButton_clean.setText(_translate("MainWindow", "清除"))
